### ISSUE TITLE
Extension: agate-geo

### ISSUE THREAD

**Issue by rdmurphy** [wireservice/agate#340]
This _feels_ like something that should exist. :grin:

Still trying to imagine what a feature set for this would look like. I really like what something like [Turf.js](http://turfjs.org/) offers in the Node.js world — would something in the agate ecosystem like that be useful, or does the current geo-ecosystem in Python already serve this need well?

I think your comments about about `numpy` and `pandas` can echo here as well —there are a few really good, expansive geo-hammers out there, but what if you only have a couple nails to hit?

**Comment by onyxfish** [comment]
I agree, though I'm also not sure where the line is. Maybe we can use this thread to list some theoretical features we would like to see in such a thing? Converting between CSV/GeoJSON/Shapefile/etc seems like an obvious start.

**Comment by rdmurphy** [comment]
Agreed. Being able to generate different representations of data would be nice. Maybe it also picks up the ability to populate a `Table` from a GeoJSON file (and other geographic representations)? I think being able to do basic queries would be cool too. Like:

- Which one of these Points is closest to a given Point?
- Does this Point fall within any of these Polygons?
- What's the area of all these Polygons?

I think a big decision to make is as to whether we defer to using another libraries' representation of geographic data (Point, Polygon, etc.), or we roll our own. I could see things like `Point`, `LineString` and `Polygon` potentially being their own `DataType`s like the ones you find in `agate` proper. Then you could go in the direction of avoiding other, non-Python requirements.

Or, should we expect folks to have things like GDAL or GEOS installed? If so, that opens the door to other libs like [Shapely](https://github.com/Toblerity/Shapely), [Fiona](https://github.com/Toblerity/Fiona) and [rtree](https://github.com/Toblerity/Rtree).

**Comment by onyxfish** [comment]
I'm really of two minds about this.

Mind A says:  Reimplementing all the geographic types and all their algorithms from scratch seems hard to justify to me. Geographic algorithms are one case where even for simple operations performance might actually matter. (I honestly have no idea how pure Python implementations of these algorithms would scale.) One wrinkle: It's not obvious how these data types would be implemented? It seems like they might need custom `Column` instances in order to proxy the data to a third-party representation, which is something I've moved away from.

Mind B says: having a Python native implementation of those geodata algorithms would be a very interesting thing from a purely educational perspective. And, it has always bothered me that geodata libraries tend to treat geodata in isolation, rather than as one part of a heterogeneous table structure. What's more, there is always value in having consistent implementations. So if somebody really wanted to work this out, I think it could be awesome.

I'm about 60/40 toward Mind A right now, but I could be persuaded either way. Certainly in either case the ability to read table data from a shapefile or geojson file seems valuable.

As with anything my gut says we need a prototype to react to. Perhaps just a Point datatype implemented as a tuple of Decimals then a distance algorithm?

**Comment by rdmurphy** [comment]
I've poked on this a bit - I wasn't sure if I should go all out and open a repo yet, so I've [dumped the code into a gist](https://gist.github.com/rdmurphy/f4407b3b1ebffc940b1d).

And so far - it works! I created a function that implements the [Haversine formula](https://en.wikipedia.org/wiki/Haversine_formula) for calculating distance between two points. I then created a new function on `Table` for getting the `Row` nearest to a point and created a `Computation` that calculates each `Row`'s distance from a point and adds that value to the `Row`. I didn't touch data types at all.

(I didn't include it, but I'm patching this functionality in using the same method you did it in agate-sql.)

Here's what came to mind while I worked on this:

- How would a geographic data type work? How would it get added to the `Table`?

Every other `DataType` has a pretty direct analog to the built-in types, so when you use something like `TypeTester`, it can figure things out. But something like a coordinate (or set of coordinates) is different. It's effectively a list of `Float`'s. Is there/should there be a way to "guess" that a column is meant to be a `Point`, or `Polygon`, or something similar? Or should it always be explicit?

Another idea that came to mind - if it makes more sense for `TypeTester` to never try to guess at geographic features, should it be a explicit step for *after* creating a `Table`? Essentially a `Computation` that creates a geographic column out of other fields that already exist. (E.g. Here is my latitude, here is my longitude, create a `Point` `Column`. This could extend to "read this string of geojson, create the proper geographic data type from it," etc.)

- Does [`python-geojson`](https://github.com/frewsxcv/python-geojson) already do what we need from a `DataType` standpoint?

It doesn't have any geographic library dependencies and adheres closely to the spec. It even could help with abstracting away some of the "convert to GeoJSON" aspects of it.

**Comment by onyxfish** [comment]
This looks great! That's a wonderfully readable haversine.

I think your idea about not having `TypeTester` attempt to infer geo-types is probably correct. It's not clear that they even *can* be automatically distinguished from normal types in all cases. And in the most common case latitude and longitude will probably be in different columns anyway.

That being the case, I like your idea of using computations to create geo-types. It's especially nice because it means the core library can stay agnostic of those additional types. (Which is something I've had my fingers crossed about. Supporting pluggable types in core is something I've put off until it became an issue.) Their might be some syntactic sugar we could put on top to hide the compute, if it feels worthwhile. (`Table.geometry('column_name')`)

If we can make `python-geojson` work as the type supplier I think that's fantastic. I'd love to defer as much of that logic as possible. We probably still will want "agate-native" `DataType` wrappers for each class  (or one generic `Geometry` type wrapper) just in case that implementation is ever extended to support formatting (which I think it will be).

Regarding a Distance DataType, I think that speakers to a larger problem of how these data types get serialized. If metadata needs to travel with them (such as a unit) that seems to break the CSV serialization. Perhaps geo types always serialize as GeoJSON, even if its embedded in a CSV? (Rather than as lat, lng columns for instance?)

I'll keep noodling on it. Lots of good ideas. If we find spots where the core agate needs to be extended to support this case I'm definitely willing to do that.

**Comment by onyxfish** [comment]
.@brianboyer suggests calling this [`geode`](https://pypi.python.org/pypi/geode) and I can not argue with that.

**Comment by onyxfish** [comment]
He also included this visual reference:

![Rocks](http://www.allenergyrocks.com/msc/avactis-images/SquareAmethystGeodeBlessed1.4.jpg)

**Comment by brianboyer** [comment]
[image: Inline image 1]

**Comment by rdmurphy** [comment]
omg, can we grab that now? So good @brianboyer. :grin:

I can poke a bit more on the `python-geojson` aspect of it, too. The more I look at that library the more awesome it becomes. There's a [Python protocol for geo data](https://gist.github.com/sgillies/2217756)! And other libraries already adhere to it. And it already implements [encoding/decoding](https://pypi.python.org/pypi/geojson/#geojson-encoding-decoding) and [validation](https://pypi.python.org/pypi/geojson/#validation).

Re: `Distance` — I was more referring to what a distance calculation like `nearest` or `distance` returns. Right now it's just a `Number()`, but there's no way to know what the unit of that number unless the column is purposively labeled. Maybe that's okay? Like, if a `Distance` type is being converted to string for CSV serialization, maybe it could automatically get the measurement descriptor appended? (`<Distance: 4321 miles>` gets serialized to `4321 miles`/`4321 mi`, `<Distance: 321 kilometers>` to `321 km`) The more I talk about this the more I have a gut feeling it's a bad idea. :grimacing: 

100% agree about serialization to GeoJSON otherwise though. I think it's the most bulletproof/portable way to do it.

**Comment by onyxfish** [comment]
You're the one doing the hacking, feel free to grab that namespace! (I have no strong preference whether it's `agate-geode` or just `geode`.) Of course, I can register it and grant you admin if you prefer.

Love that there is already a data spec for this. I totally agree we should support the known standard if it's possible--especially if that means we can piggyback on existing mathematical implementations.

I think you're gut about serializing the unit is correct. Though I'm also not sure what the best alternative is. For instance, how do we handle projections? I think my intuition is that it's too hairy of a problem and we just don't. Everything gets serialized as naive numbers and you leave it to the user to sort out their own metadata. Maybe?

**Comment by rdmurphy** [comment]
A small update — I grabbed [geode](https://pypi.python.org/pypi/geode/0.1.0). Nothing built yet, tho. :smile:

**Comment by onyxfish** [comment]
All great libraries begin with great namespace.

**Comment by lcorbasson** [comment]
Hi @rdmurphy, did you make any progress towards this, apart from the aforementioned gist?

I'm looking for something similar and might hack a bit on it...

**Comment by jpmckinney** [comment]
Closing as this would be a separate library.
