### ISSUE TITLE
Need a fast way to normalize/standardize/slugify column names

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#466]
See onyxfish/csvkit#396

**Comment by onyxfish** [comment]
We should pull a known good slugifier into `utils`, such as the one used in Django. Then this could be a flag to the constructor or a method similar to `rename`.

**Comment by onyxfish** [comment]
Maybe https://github.com/un33k/python-slugify

**Comment by onyxfish** [comment]
Could also lead to a `Slugify(columns)` computation, which would be handy.

**Comment by onyxfish** [comment]
Note, that slugger doesn't handle uniqueness, but this one does: https://github.com/dimka665/awesome-slugify

**Comment by nbedi** [comment]
@onyxfish added `slugify` into `utils`. It wraps around https://github.com/dimka665/awesome-slugify.

A flag to the constructor and a whole new method felt off to me. Ended up adding it as an option to `Table.rename` since it feels like an advanced functionality of renaming and had the best of both. Let me know what you think and if I should adjust.
