### ISSUE TITLE
Should agate and extensions be moved to its own GitHub org?

### ISSUE THREAD

**Issue by nbedi** [wireservice/agate#477]
With extensions growing, it might be easier for new users and developers to have all of agate in its own place. I may not be aware of possible cons though. Thoughts?

**Comment by onyxfish** [comment]
Yes! In fact, this I've been noodling on ideas for what to name such an organization. The current plan would be for it to include agate, all the agate extensions built so far, and csvkit. There area couple other small things that may get folded in too, such as `ffs`.

**Comment by nbedi** [comment]
:+1: sounds great!

**Comment by onyxfish** [comment]
Currently leaning towards: https://github.com/wireservice

**Comment by nbedi** [comment]
mojo? https://www.youtube.com/watch?v=nPms9Lmi4LU

**Comment by onyxfish** [comment]
I've started moving repos over to the new org. @nbedi and @jpmckinney, this shouldn't interrupt your workflows since things will redirect, but let me know if anything wacky happens. I'm moving them one at a time so I can update links as I go. Once I've got things moved over I'm going to add you gentlemen as collaborators on the org, rather than the individual repos. That way you can fix bugs that span the projects. (This may take me a few days.)

**Comment by onyxfish** [comment]
Here is the list of projects yet to be migrated, as of now:

* agate
* csvkit
* agate-dbf
* agate-excel
* agate-stats
* agate-sql
* proof
* ffs

**Comment by onyxfish** [comment]
All projects moved over. Teams created. @nbedi @jpmckinney invited. README's updated. Read the docs updated. Done!
