### ISSUE TITLE
Pivot / De-normalize / Crosstabify

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#493]
This week we've been experimenting with agate on a real newsroom project for the first time. 

We're newbies, so it's possible we're missing obvious stuff, but one thing we're struggling to figure out is how to compute crosstabs. 

Here's a simple example dataset with a list of people along with each's race and gender

```python
import agate
column_names = ['name', 'race', 'gender']
column_types = [agate.Text(), agate.Text(), agate.Text()]
rows = (
    ('joe', 'white', 'male'),
    ('jane', 'white', 'female'),
    ('josh', 'black', 'male'),
    ('jim', 'latino', 'male'),
    ('julia', 'white', 'female'),
    ('joan', 'asian', 'female'),
)
people = agate.Table(rows, column_names, column_types)
```

Right now, it's awesome how easy it is to group and count by either race or gender.

```python
by_race = people.group_by("race")
totals = by_race.aggregate([
    ('total', agate.Length()),
])
totals.print_table()
```
```text
|---------+--------|
|  race   | total  |
|---------+--------|
|  white  |     3  |
|  black  |     1  |
|  latino |     1  |
|  asian  |     1  |
|---------+--------|
``` 
```python
by_gender = people.group_by("gender")
totals = by_gender.aggregate([
    ('total', agate.Length()),
])
totals.print_table()
```
```text
|---------+--------|
|  gender | total  |
|---------+--------|
|  male   |     3  |
|  female |     3  |
|---------+--------|
```

But what we're having trouble figuring out is how to combine those two things into a cross tab. Basically, the table we want it to output is this, which I've handcrafted.

```text
|---------+--------+--------|
|  race   | male   | female |
|---------+--------+--------|
|  white  |     1  |    2   |
|  black  |     1  |    0   |
|  latino |     1  |    0   |
|  asian  |     0  |    1   |
|---------+--------+--------|
``` 

If there's a way to do it in agate, we were unable to find it in the documentation. Please forgive us if we are overlooking it. 

What we've done so far is a really ugly hack to create a data dict on the fly and join it to the table.

```python
by_race = people.group_by("race").aggregate([
    ('total', agate.Length()),
])

gender_by_race = {}
for row in by_race.rows:
    race = row[0]
    gender_by_race[race] = {
        'male': len(people.where(lambda r: r['race'] == race and r['gender'] == 'male').rows),
        'female': len(people.where(lambda r: r['race'] == race and r['gender'] == 'male').rows)
    }

totals = by_race.compute([
    ('male', agate.Formula(agate.Number(), lambda r: gender_by_race[r['race']]['male'])),
    ('female', agate.Formula(agate.Number(), lambda r: gender_by_race[r['race']]['female'])),
])
totals.print_table()
```

There must be a better way, right?

**Comment by nbedi** [comment]
I believe there isn't at the moment but @onyxfish can correct me if I'm wrong. I was going to tackle #492 and #487 today to fix that.

**Comment by onyxfish** [comment]
Neil is correct. At the moment there is no built-in way to do this. I've held off on implementing it as long as possible because it's one area where there is profoundly little consistency about how different software approaches this. I've been hoping to have some grand epiphany how to implement these sorts of things in a simple and generalized way, but so far it hasn't really come to me. I'm excited to see what Neil comes up with.

**Comment by onyxfish** [comment]
Coming back to this for a moment. I want to point out that crosstabs a little funny because they are lossy. There is a way to get the same information you want with a lossless table structure:

```
by_race_and_gender = people.group_by("race").group_by("gender")
counts = by_race.aggregate([
    ('count', agate.Length()),
])
counts.print_table()
```

Output:

```
|---------+--------+--------|
|  race   | gender   | count |
|---------+--------+--------|
|  white  |     male  |    1   |
|  white  |     female  |    2   |
|  black |     male  |    1   |
|  ... |     ...  |    ...   |
|---------+--------+--------|
...
```

When I've considered this issue before I've always gotten hung up on whether we should encourage people to transform their data into a format that potentially throws away other data in the table. That being said, I'm understanding more and more that this is a really useful format for a human-readable output, and should probably be supported as such.

**Comment by onyxfish** [comment]
Actually, it's probably unfair to say that other table structure is lossless. It also squeezes out other columns, but it's feasible to attach other aggregates, whereas in a cross-tab you're limited to the relationship of two series.

**Comment by nbedi** [comment]
I'm currently leaning toward your output because it'd be easier stack multiple columns/aggregates. I will put this all in a pull request so we can review it. Should be in by EOD.

**Comment by onyxfish** [comment]
Just to be clear, that example I posted already works.

**Comment by nbedi** [comment]
Sorry, I got myself mixed up. I originally opened #492 thinking of it as a complete inverse of #487 which isn't exactly crosstabs and may not be particularly useful.

**Comment by palewire** [comment]
I don't totally understand the underlying concerns about the table object, though I'm sure they are significant. What I will say is this kind of crosstab is what people here in our newsroom expect to be able to make. 

One approach, which I sometimes take with SQL, might be an intermediary step. 

If I am looking to create columns that are the result of counts on filters subsets of the table I will create a new computed column on the fly that combines and aggregate function and a CASE statement. 

For this example, it might look something like this:

```sql
SELECT 
  race
  SUM(CASE WHEN gender = 'male' THEN 1 ELSE 0) as male,
  SUM(CASE WHEN gender = 'female' THEN 1 ELSE 0) as female
FROM my_table
GROUP BY race
```

I wonder if there might be a way to pass a lambda function into the existing ``Length`` computation to achieve something like the table I created above. I'm just imagining code here but I'm curious what you'd think of it.

```python
by_race = people.group_by("race").aggregate([
    ('male', agate.Formula(agate.Number(), lamdba row: row['gender'] == 'male')),
    ('female', agate.Formula(agate.Number(), lamdba row: row['gender'] == 'female')),
    ('total', agate.Length()),
])

The obvious downside of anything like this is I have to explictly list each new column. On a classic PivotTable those are created dynamically. In reality, I think it would ultimately be nice to have both options.

**Comment by onyxfish** [comment]
I figured out this has been so confusing `pivot` and `normalize` are not opposites. There is now a `denormalize` method, which `pivot` leverages for it's higher level functionality. Arbitrary aggregations are working. Take a look at the tests and lemme know what you think. See also new ticket #511 for a lingering detail.

**Comment by nbedi** [comment]
Tests look good to me. Still wrestling with the idea of a `computation` param. It's obvious now that we'd just apply it right on the pivot column before denormalizing but the varied inputs are still a problem. We'd have to limit it to `Computation`s that can accept a single column name as input (like `Percent`).

Maybe `missing_value` should be named `default_value` in denormalize and pivot (but no strong preference).

This is so much cleaner with the denormalize method. Jealous I didn't think of that. :+1:

**Comment by onyxfish** [comment]
Right, the `Computation` part is harder. I had mistakenly thought I had solved that with this, but I see now it's still an issue.  I think you're on the right track w/r/t to applying it to the pivot column before denormalizing. It makes sense that we would only support those computations that take a single column arg, but I'm not sure about a good *contractual* way to enforce this...

I renamed `missing_value` to `default_value`. Def better.

**Comment by onyxfish** [comment]
Pushed experimental `Computation` support on master. It seems to work, though I'm not sure I love it. It relies on a "magic" argument to the computation constructor. (I also tried it with the argument automatically supplied and kwargs passed through the constructor, but that seemed even less obvious.)

Tired now, maybe will have better ideas in the morning.

**Comment by nbedi** [comment]
Yeah something like this implementation was all I could think of and I was also not 100% in love but it does work. Hoping an alternative to the "magic" argument/passing 'pivot' to the Computation will pop out at one of us.

@palewire when you have a chance can you look at pivot and tell us what you think? Want to make sure we hear your thoughts since you opened this thread. #508 shows how it can be used as `counts` and `percents`. Thanks!

**Comment by onyxfish** [comment]
Wrote up documentation: http://agate.readthedocs.org/en/latest/cookbook/transform.html

**Comment by onyxfish** [comment]
After writing the documentation I'm finding that the magic argument name bothers me less. We'll see if that feeling changes after I use it for a bit.

**Comment by onyxfish** [comment]
I just used denormalize in a real project. Game changer. This is just super awesome.

**Comment by onyxfish** [comment]
Okay, I feel good about this. Closing out. Please reopen or open new issues if anybody spots a problem.

**Comment by palewire** [comment]
I love all this progress and the general direction but there are a couple small points I'd like to raise based on quickly reading the documentation. Forgive me for being lazy, but in some self-exculpatory sense a quick read like mine is similar to how beginner users will approach your library.

**It isn't obvious to me why a ``Count`` is added as a new column by default.** That assumes some kind of deep connection with the word "pivot" that I have just never had. To me, a pivot table has always meant a group and calculate, with the what is calculated being open-ended. In my experience, a generic group and count has typically be referred to in newsrooms as a "frequency." At least to my eyes, having it suddenly pop on a new column called "pivot" is magic. 

**I'm not clear how this can handle some of my most common use cases.** More than anything else, the most common thing I personally like to do with pivot tables is group on a particular column and then tack on a series of columns, like count, percent, average, min, max, quartile1, etc, that give me descriptive statistics about each group. How would I go about doing that here?

**Comment by onyxfish** [comment]
You're a hard guy to please, Ben. :wink: I think the problem here is that Excel (and other spreadsheet programs) have loaded up the pivot table feature with all kinds of complex functionality. The "cross-tabulation" case we've implemented here is, in my mind, the distinguishing feature of a pivot and is the part that agate did not support at all until now. The "summary" case that you're describing, where columns of different types are mixed in, is already possible with agate in 2 statements:

```python
tableset = table.group_by('foo')
summary = tableset.aggregate([
   ('mean', agate.Mean('bar')),
   ('median', agate.Median('bar')),
   ('mode', agate.Mode('bar')),
])
```

Excel allows you to mix and match "cross-tabulation" and "summary" cases, but that's only possible because they allow for "sub-columns" and "sub-rows", at which the data is no longer truly a table, but rather a hierarchy displayed on a grid. We certainly aren't going to support that.

On the other hand, I agree that the magic "pivot" column name is somewhat confusing. We can add an argument to override that. (#518). I'm open to ideas for smarter defaults that `pivot`. We could have it default to the class name of the aggregation, which would make the default `Length`. Or we could hardcode `count` in there...

**Comment by palewire** [comment]
Interesting to hear your thoughts on this. Maybe I'm off on a limb here, but perhaps you should consider calling the method ``crosstab`` instead of ``pivot`` to distinguish it more clearly from Excel. Might help avoid confusion.

IMHO, if what the "pivot" column does is a count, it should just be called count.
