### ISSUE TITLE
It would be cool if Table had a ``percents`` method that was like ``counts``

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#497]
I was pretty stoked today to discover that [Table.counts()](http://agate.readthedocs.org/en/1.2.2/api/table.html#agate.table.Table.counts) exists. Would you be open to me trying to submit a similar method for the new ``Percent`` computation called maybe ``Table.percents()``?

**Comment by nbedi** [comment]
Would Table.percents() be a higher level method for this:

```
Table.counts().compute([
        ('percent', agate.Percent('count'))
    ])
```

**Comment by palewire** [comment]
Yes. Exactly. I'm imagining something coming out like:

```
table.counts("race").percents("count).print_table()
```

and it feels glorious. I even described it to a pandas user and they turned green with envy.

What me to try a pull request?

**Comment by nbedi** [comment]
Another decision at the weird intersection of improving human usability and adding to code bloat. Deferring to @onyxfish once more but should have a better handle on these after I hear his thoughts.

**Comment by onyxfish** [comment]
Not loving the trend this sets toward shortcut methods. Seems to violate the Zen of Python line 13 to me. However, see #508 for a possible solution.

**Comment by palewire** [comment]
This is obviously a subjective design decision, and lord knows it's your call to make and not mine.

However, when it comes to the Zen of Python, I would argue that this:

```python
table.percents("count")
```

is much more "obvious way to do it" than this:

```python
table.compute([('percent', agate.Percent('count'))])
```

And I think that's especially true for beginners. 

As part of experimenting with agate here in our newsroom over the past couple weeks, I've been using it as a route to ween a long-time SAS user off its expensive proprietary system and into Python. 

It's my impression that serving this kind of user, who has some programming sense and experience but is far from an expert on Python, is a top priority.

What I've seen that creating a compute list to add new columns is not immediately obvious, largely because it requires understanding the mechanics of the nested tuple configuration for each column. It strikes me, a more experienced Python programmer, as an elegant solution, but to a beginner I believe it's just a finicky lot of brackets and ideas to parse. 

That's why when I first encountered the ``counts`` method I was so pleased. 

Not only is it easy for a beginner to grok, it's also easier for a more advanced user to grip and rip when quickly writing a script of middling size. Even for me, who has been writing Python for 10 years, I had to go back and look at the docs repeatedly to make sure I was configuring my compute arguments correctly.

**Comment by onyxfish** [comment]
I hear you, but my reference to the Zen was more about "one right way". In my experience shortcut methods lead to greater confusion over the long term. First, because that user will eventually wonder why the hell there are two ways to do exactly the same thing. And second, because `table.percents("count")` is only obvious if it happens to align with your expectations. Percent of what? Of the sum? Of the distribution? If I have to look at the documentation anyway, why not just lookup up the other way of doing it?

More generally, as a maintainer, shortcut methods tend to lead to a slippery slope of spaghetti code. If there is a shortcut for counts and percents, why not one for every computation? Why not table summary methods? Eventually, these become difficult to support and, as has been a frequent problem with csvkit, it becomes almost impossible to say no to adding shortcut methods into core.

And lastly, all of these cases can be easily supported by an extension, if you or anybody else really think they are essential. `agate-easy` or whatever. I'm certainly not going to stand in the way of providing tracks for users to arrive on, but I do think it should be explicit that the methods they are using are just wrappers around the "one right way."

The elegance of #508 is that I think we can arguably support all of these cases with one pretty simply method, which I'm hopeful will strike a better balance between obviousness and hygiene.

**Comment by palewire** [comment]
Alrighty. It is true that is you open this door today I'd asking for ``table.ranks("percent")`` tomorrow.

Interested to see how ``pivot`` works out. I guess I should withdraw my pull request in #501.
