### ISSUE TITLE
Is there no way to edit values?

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#499]
If not, it might be a good idea to say this good and loud in the documentation. 

Here's where it came up for me: My input table has a semi-dirty field with coded values that recur through the set. Four out of the fives values are dandy. But the fifth one I'd like to rename to sanitize things a little before I do a group and count. How would you recommend going about that?

**Comment by nbedi** [comment]
It mentions mutability in the [principles section](http://agate.readthedocs.org/en/1.2.2/contributing.html#principles) but it might be a good idea to highlight these principles earlier in the documentation. The inability to access/modify data is by design.

Right now, the right way to clean data would be to start with a `raw_data` table then produce a `clean_data` table by applying a custom Formula computation on each row. Something like:

```
strip_spaces = agate.Formula(lambda r: r['raw_column'].strip())

clean_data = raw_data.Table.compute([
    ('clean_column', strip_spaces)
]).exclude('raw_column')
```

This also makes your cleaning process reproducible so there's always a path in code from raw data to final analysis.

**Comment by palewire** [comment]
Got it. One thing that I would have found helpful as a newbie is if the actual Python traceback error just told me this. That's what Django does more and more with things like DeprecationErrors. Provide a more fulsome explanation, maybe a good sentence, and then print out a hyperlink to the full documentation explaining why.

Want me to try a pull request?

**Comment by nbedi** [comment]
Sure sounds good to me!

**Comment by csessig86** [comment]
Just a quick note: Agate now requires you to specify the data type as the first argument of agate.Formula. So I had to change this:
`strip_spaces = agate.Formula(lambda r: r['raw_column'].strip())

To this:
`strip_spaces = agate.Formula(agate.Text(), lambda r: r['raw_column'].strip())

I figured I'd comment just in case someone stumbles across this in the future.
