### ISSUE TITLE
Encoding issue with test.csv when printing table on Windows 7 w/ vanilla Py2.7

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#556]
agate 1.3.0 w/ `examples/test.csv`

![ie11 - win7](https://cloud.githubusercontent.com/assets/33046/13605821/fdc1ed90-e50e-11e5-84a8-d71f611db1b4.png)

@mattwaite you seen this?

Do we need to be specifying in the docs that windows folks need to set their terminal to unicode OR [detecting the CLI encoding](http://stackoverflow.com/questions/6344853/python-unicode-in-windows-terminal-encoding-used) and outputting that?

**Comment by mattwaite** [comment]
I have not seen that error specifically, but I have had zero luck making the default command prompt work because of similar encoding issues. I had students install Git -- [http://git-scm.com/](http://git-scm.com/) -- which comes with Git Bash on Windows and use that. I haven't had a problem since and haven't had time to go back at it to see if I could make the default command prompt work with the work you and @palewire did with the last Window's weirdness.

**Comment by mattwaite** [comment]
Wait wait wait, I'm wrong. I have indeed seen that error before. There is a character in the file that Mac/Linux character maps have and Windows does not. There are several such characters, I found, but the issue I found was that the specific character was in the CP-1251 character encoding and needed to be UTF-8. I solved it by running the file through iconv, which Linux has by default. On Windows, it comes with Git Bash. The specific step I ran was iconv -f CP-1251 -t UTF-8 infile.csv > outfile.csv The outfile imported fine in windows after that.

**Comment by palewire** [comment]
Interesting. That's a bug we didn't see.

**Comment by onyxfish** [comment]
So, looking at this a little closer, I gather this error is not a code problem, but rather because I have 👍 in my test file and the default command line encoding doesn't have a comparable character. Other than user-side fixes, I think the only thing that could be done is to drop unmappable characters, which seems all kinds of wrong. That being the case, I'm going to close this out.
