### ISSUE TITLE
Why does `Table.bin` convert Number to Text for the label column in the output table?

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#569]
I think there was a reason why I did this, but it does seem wrong.

Via @livlab: https://docs.google.com/document/d/1dVG876aVZoDxW5RyWBM7kC1ZTyPTrWqKBJctLuAh7gs/edit?ts=56e71c0e

**Comment by nbedi** [comment]
@livlab these notes are great, thanks for writing them!

**Comment by nbedi** [comment]
@onyxfish @livlab I think this is a non-issue since the label column is Text to display a range like `[0 - 10)`. 

To answer the first question in the doc, `Table.bins` is called on the `exonerations` table where `age` is a Number column. `age` is a Text column in the outputted `binned_ages` table because it is a label.

**Comment by jpmckinney** [comment]
This is described as a non-issue, so closing.
