### ISSUE TITLE
Be more explicit about by-design agate limitations

### ISSUE THREAD

**Issue by nbedi** [wireservice/agate#590]
Opening a new issue to expand on @palewire's point in #586.

There are places in docs that touch on some of these kinds of limitations but we could probably be more explicit/helpful about them in a few ways:
- Add warnings like the one mentioned in https://github.com/wireservice/agate/issues/586#issuecomment-203453076
- Add something like "Why not agate" to the about page under "Why agate"
- Add references to libraries that do optimize for these limitations

**Comment by onyxfish** [comment]
Good idea. Notes:

* I'm pretty leery of the idea of a warning. There are a huge number of variables that can impact individual performance, so that seems like the wrong solution to me. 
* Let's not be too aggressive in drawing a box around what agate "can't do". Well I'm cognizant of @palewire's concerns, I feel strongly that 300MB data is simply not *normal*. We should do everything we can to encourage users to try agate, while also being up front that edge cases, by their very nature, will nearly always require specialized tools. The relationship between agate and pandas, for example, is not much different than the relationship between Postgres and Hadoop. At a certain point your problems are harder than any general-purpose tool is going to solve.
* I do very much like the idea of explicitly suggesting other solutions for particular needs: high throughput, time series analysis, high-memory datasets, etc. Anything we can do to help channel people toward solving their problem is a valuable addition to the docs.

**Comment by palewire** [comment]
Maybe there's a sweet spot in between. Could a MemoryError include a
friendly error message that points to these proposed docs?

**Comment by onyxfish** [comment]
That's a good intuition, but I think it's going to be very tricky to realize. The `MemoryError` you encountered is a Python native error, not something in agate, so I have no control over when it gets thrown. Short of wrapping the entire library in an exception handler, I'm not sure how I can effectively catch it.

**Comment by palewire** [comment]
Welp. I guess I had some fantasy there was a line where files got read in
via open and looped or something that could be wrapped.

**Comment by onyxfish** [comment]
You could catch that one particular case, but there's nothing to say you wouldn't hit a `MemoryError` on the very first operation you tried to run on the dataset. In fact, the latter is probably a far more common case.

**Comment by jpmckinney** [comment]
We addressed this issue in csvkit, because it came up a lot. If it comes up more frequently in agate, we can add similar wordings. In the meantime, this seems like an infrequent issue, such that it doesn't yet need docs, so closing.
