### ISSUE TITLE
Cookbook: removing a column (`select` and `exclude`)

### ISSUE THREAD

**Issue by lindzcook** [wireservice/agate#592]
There doesn't appear to be any documentation on the best way to delete a column. Would seem to belong [here](http://agate.readthedocs.org/en/1.3.1/cookbook/columns.html) where the docs discuss reordering and renaming columns.

Right now I am using select to create a new table with the other columns selected, but this doesn't seem like the most efficient way.

**Comment by nbedi** [comment]
[Exclude](http://agate.readthedocs.org/en/1.3.1/api/table.html?highlight=exclude#agate.Table.exclude) might be the more intuitive method to use here. You won't be able to actually delete the columns because agate tables are immutable but this will create a new table without the specified column (so very similar to what you're doing with select, the arguments will just make more sense).

Surprised `exclude` is not in the cookbook though, should definitely be somewhere under the `basics` section. Changing issue title to address that.

**Comment by onyxfish** [comment]
Yep, exclude is what you want. It is an oversight that this is missing from the cookbook.
