### ISSUE TITLE
Can't group_by Boolean datatypes

### ISSUE THREAD

**Issue by palewire** [wireservice/agate#627]
If I run this:

```python
import agate

rows = [
    dict(bool=True, number=1),
    dict(bool=True, number=1),
    dict(bool=False, number=1)
]
column_types = (agate.Boolean(), agate.Number())
table = agate.Table.from_object(rows, column_types=column_types)

table = table.group_by("bool").aggregate([
    ('sum', agate.Sum('number'))
])
table.print_table()
```

I get this error:

```python
Traceback (most recent call last):
  File "scratch.py", line 12, in <module>
    ('sum', agate.Sum('number'))
  File "/home/ben/Code/agate/agate/tableset/aggregate.py", line 81, in aggregate
    return Table(output, column_names, column_types, row_names=row_names)
  File "/home/ben/Code/agate/agate/table/__init__.py", line 180, in __init__
    raise ValueError('Row names cannot be of type int. Use Decimal for numbered row names.')
ValueError: Row names cannot be of type int. Use Decimal for numbered row names.
```

But I change the data type of the first column to ``Text`` it works.

```python
import agate

rows = [
    dict(bool=True, number=1),
    dict(bool=True, number=1),
    dict(bool=False, number=1)
]
column_types = (agate.Text(), agate.Number())
table = agate.Table.from_object(rows, column_types=column_types)

table = table.group_by("bool").aggregate([
    ('sum', agate.Sum('number'))
])
table.print_table()
```
```bash
|--------+------|
|  bool  | sum  |
|--------+------|
|  True  |   2  |
|  False |   1  |
|--------+------|
```

That seems wrong to me. My gut says users should be able to group by boolean columns just as they do text columns.

**Comment by nbedi** [comment]
Yup nice catch, seems like a bug with the [check for int row names](https://github.com/wireservice/agate/blob/master/agate/table/__init__.py#L179). 

isinstance([a boolean value], int) returns True. That condition should be changed to also check the value is not a boolean. 

(It does itch a tiny bit because row names are [not checked for uniqueness](https://github.com/wireservice/agate/issues/614) and with two unique boolean values this could lead to silent issues. But boolean row names should work so fixing this condition still makes sense.)

**Comment by nbedi** [comment]
Will also have silent issues if row names contain `True` and `Decimal('1')` but that falls under #614 too.

**Comment by palewire** [comment]
Now there's a bug I never considered! Thanks for this fix.
