### ISSUE TITLE
tutorial clarification - minor

### ISSUE THREAD

**Issue by sandrafish** [wireservice/agate#630]
in the [SQL cookbook](http://agate.readthedocs.io/en/1.4.0/cookbook/sql.html) portion the following: 
new_table = table.select(('state', 'total'))

should have inner brackets instead of two parens (same for the Chain commands together section on that page)

new_table = table.select(['state', 'total'])

**Comment by nbedi** [comment]
Nice catch, thank you!

**Comment by nbedi** [comment]
The parens will actually work because any kind of sequence will work for most agate methods expecting a sequence. I might still change them to brackets to be consistent with the rest of the docs.

**Comment by sandrafish** [comment]
thanks! actually, the double parens wasn't working for me - needed the inner curlies...

**Comment by nbedi** [comment]
That's odd, can you show me the code with the double parens that wasn't working? I changed it to be consistent anyway and it'll be fixed online in the next release.

**Comment by sandrafish** [comment]
it's on some of my own stuff, not tutorials, that i'm working on:

bail_id = bail.select({'inmate_id'})

**Comment by nbedi** [comment]
Ah it's because you're only selecting a single element. Tuple syntax needs a trailing comma with parens for a single element (https://wiki.python.org/moin/TupleSyntax). 
The easy solution is to just ditch the second parens or brackets for searching just one element:
`bail_id = bail.select('inmate_id')`
The cookbook had multiple elements so it was still technically valid. Let us know if you have any other problems!
