### ISSUE TITLE
Is there a way for Chinese to pretty print?

### ISSUE THREAD

**Issue by scottming** [wireservice/agate#639]
![1](https://cloud.githubusercontent.com/assets/12830256/19876213/de49f5c8-a00e-11e6-90ca-bc5800e5c51a.png)
![2](https://cloud.githubusercontent.com/assets/12830256/19847568/d68fc36c-9f82-11e6-8924-42c7e2242242.png)

I'm using Python3. The second image show that `name` column is Chinese, and the table is not pretty. Is there a way to fix it?

**Comment by onyxfish** [comment]
Huh, that's a great question. Off the top of my head I'm not sure, but there should be some way to count the glyph width rather than the character count. We'll look into it.

**Comment by onyxfish** [comment]
Unfortunately, from [what](http://stackoverflow.com/questions/22225441/display-width-of-unicode-strings-in-python) I'm [reading](http://stackoverflow.com/questions/4622357/how-to-control-padding-of-unicode-string-containing-east-asia-characters) it seems this is not solvable as it is actually an issue with terminal fonts, rather than with the the code. In short, monospace fonts are supposed to guarantee that characters take up one width, but for East Asian characters they often break their own design and use two.

Without writing some really crazy font-parsing code, I don't think it's fixable. On the plus-side, in agate 1.5.0 the tables we pretty print will be [markdown-friendly](https://github.com/wireservice/agate/issues/626), so if you copy and paste them into a markdown document they should format correctly.

Sorry I don't have a better solution. Closing this out for now.
