### ISSUE TITLE
Is it worth having an `agate.Null` data type?

### ISSUE THREAD

**Issue by onyxfish** [wireservice/agate#657]
Would resolve issues like #371 and also be useful for, e.g. csvstat output.

**Comment by onyxfish** [comment]
Experimentally implemented on `null` branch. Not sure if this is a good idea or not.

**Comment by nbedi** [comment]
Feels a little odd because my completely `null` columns are really either Boolean or Text. But this could help by adding an intermediate step rather than agate guessing one or the other. Maybe it should even throw a warning if TypeTester creates a Null column.

Could be useful if there was a computation or method that converted an `agate.Null` column to a given column type.

**Comment by onyxfish** [comment]
Yeah, no. A warning is a good idea, but creating a whole different type is overkill.
