### ISSUE TITLE
print_table should not fail on rows with unequal columns

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/agate#666]
Reticketed from https://github.com/wireservice/csvkit/issues/751

**Comment by onyxfish** [comment]
This is going to be very difficult to change at the agate level, because the columns are instantiated first and then populated with data. Retroactively adding columns if extra data is discovered midway through the file will be complicated. That being said, I certainly agree it would be useful, and would support a real world case.

**Comment by jpmckinney** [comment]
I'm abandoning the feature request.
