### ISSUE TITLE
Error when using agate.Median() in an aggregate function with all nulls

### ISSUE THREAD

**Issue by tf13** [wireservice/agate#714]
If you calculate a median in an aggregate function and some of the column's values are null, agate is very good about ignoring those and calculating a median anyway. However, if you do the same with a column of all nulls, agate chokes.

I ran into this because I took a large table of data, did a group_by on a field and then tried to summarize that data by running an aggregation calculating various medians, averages, etc. Some of the tables in the TableSet created by the group_by have all nulls in one of the fields I'd like to summarize (because data are still coming in in this case).

It seems it would make sense to either have all nulls yield a median of nulls, or at least offer an option for a default value if this happens.

Thanks!

**Comment by dannguyen** [comment]
Came here to post exactly this issue, but also for max, max_length, max_precision, mean, min, mode...basically anything that invokes `column.values_without_nulls()`.

What's confusing is that `Sum`, because it has a `start` value of `0`, will return `0` for entirely null columns, whereas the other aggregations will throw the error.

## Suggested solution

I guess `Sum` should remain as is, just in case existing code/projects depend on it return `0` for all-null columns. But for the other aggregations, it'd be nice if by default they returned `None` instead of an error

**Code example:**

```py
import agate
from agate.aggregations import Sum, Max
data = [
    {'name': 'Alice', 'stuff': 5},
    {'name': 'Bob', 'stuff': 4},
    {'name': 'Cal', 'stuff': None},
    {'name': 'Bob', 'stuff': 2},
]

dt = agate.Table.from_object(data)


dt.pivot('name', aggregation=Sum('stuff')).print_table()
# Output (current and expected behavior)
"""
| name  | Sum |
| ----- | --- |
| Alice |   5 |
| Bob   |   6 |
| Cal   |   0 |
"""

dt.pivot('name', aggregation=Min('stuff')).print_table()
# Proposed output, instead of raising `ValueError: min() arg is an empty sequence`
"""
| name  | Min |
| ----- | --- |
| Alice |   5 |
| Bob   |   2 |
| Cal   |     |
"""
```

Or if avoiding the ValueError by default results in breakage elsewhere, maybe the aggregations could have a keyword argument like `raise_error_on_empty_sequence=True`, that could otherwise be manually set? 

From what I can tell as a layperson in agate's source code, there doesn't seem to be another way of custom handling the exception, when calling an aggregation via `Table.pivot()`. But happy to be told otherwise :)

**Comment by jpmckinney** [comment]
`max_precision` also returns 0 on null input.

**Comment by jpmckinney** [comment]
Related: #706
